AWSTemplateFormatVersion: '2010-09-09'
Description: |
  This CloudFormation template creates IAM users and groups with specific S3 and EC2
  read-only permissions, using a static password for initial login.

Parameters:
  IAMUserNamePrefix:
    Type: String
    Description: A prefix for the IAM user names.
    Default: mylab

  StaticPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Static password for the IAM users

Resources:
  # Groups
  S3ReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "${IAMUserNamePrefix}-S3ReadOnlyGroup"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  EC2ReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub "${IAMUserNamePrefix}-EC2ReadOnlyGroup"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess

  # IAM Users
  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${IAMUserNamePrefix}-s3-user"
      Groups:
        - !Ref S3ReadOnlyGroup
      LoginProfile:
        Password: !Ref StaticPassword
        PasswordResetRequired: true
      Tags:
        - Key: Purpose
          Value: S3Access
        - Key: ManagedBy
          Value: CloudFormation

  EC2User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${IAMUserNamePrefix}-ec2-user"
      Groups:
        - !Ref EC2ReadOnlyGroup
      LoginProfile:
        Password: !Ref StaticPassword
        PasswordResetRequired: true
      Tags:
        - Key: Purpose
          Value: EC2Access
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  S3UserConsoleLoginURL:
    Description: Console login URL for the S3 User
    Value: !Join 
      - ''
      - - 'https://'
        - !Ref "AWS::AccountId"
        - '.signin.aws.amazon.com/console'
        - '?userName='
        - !Ref S3User
        - '&forceCheck=true'

  EC2UserConsoleLoginURL:
    Description: Console login URL for the EC2 User
    Value: !Join
      - ''
      - - 'https://'
        - !Ref "AWS::AccountId"
        - '.signin.aws.amazon.com/console'
        - '?userName='
        - !Ref EC2User
        - '&forceCheck=true'
